#!/bin/bash

if [ ! -p /dev/stdin ] || [ "$1" = "-h" ] || [ "$1" = "--help" ];then
  cat <<_END_
usage: ${0##*/}
read STDIN and change fore-colors only applied to spaces into back-colors
_END_
  exit 1
fi
cat</dev/stdin|sed "$(echo -e 's/\x1b\\[3\\([0-9]\\)\\(m[ \t]*\x1b\\)/\x1b\\[4\\1\\2/g')"
