#!/usr/bin/env perl

if(-t){
 $0=~s#.*/##;
 print "usage: (some-command) | $0\n get diff of diff -- difference between added and deleted\n";
 exit;
}

@line=<STDIN>;
foreach(@line){
 s/\x1b\[\d*m//g;
 if(/^[\-<]([\x00-\xff]*)/){push(@lin1,$1);}
 if(/^[\+>]([\x00-\xff]*)/){push(@lin2,$1);}
}
if(!@lin1 || !@lin2){print "no diff line found -- maybe something mistaken\n";exit(1);}
&diff(\@lin1,\@lin2);

sub diff{
 my($i,$j,$c,$ret,@line1,@line2);
 $i=0;$j=0;
 @line1=@{$_[0]};@line2=@{$_[1]};
 $ret='';
 while($i<@line1 || $j<@line2){
  if($line1[$i] eq $line2[$j]){
   $c++;
  }else{
   my($ti,$tj);
   $ti=$i;$tj=$j;
   search:while($ti<@line1 && $tj<@line2){
    $ti++;$tj++;
    my($tti,$ttj);
    for($tti=$i,$ttj=$j;$tti<=$ti && $ttj<=$tj;$tti++,$ttj++){
     if($line1[$tti] eq $line2[$tj]){
      $ti=$tti;
      last search;
     }
     if($line1[$ti] eq $line2[$ttj]){
      $tj=$ttj;
      last search;
     }
    }
   }
   if($ti>=@line1){$tj=@line2;}
   if($tj>=@line2){$ti=@line1;}
   my $f;
   print $i+1<$ti?int($i+1).",$ti":$ti;
   if($i==$ti){print "a";$f=0;}
   elsif($j==$tj){print "d";$f=1;}
   else{print "c";$f=2;}
   print $j+1<$tj?int($j+1).",$tj":$tj;
   print "\n";
   while($i<$ti){
    print "< $line1[$i]";
    $i++;
   }
   print "---\n" if $f==2;
   while($j<$tj){
    print "> $line2[$j]";
    $j++;
   }
  }
  $i++;$j++;
 }
 print "no deference\n" if $c==@line1 || $c==@line2;
}
