#!/bin/bash
if [ -t 0 ];then
 this_cmd=${0##*/}
 cat << --USAGE--
usage: (some-command) | $this_cmd
 get diff of diff -- difference between added and deleted

args:
 iteration : iteration count

options:
 -w : ignore white spaces
--USAGE--
 exit 1
fi


it=1
wflag=''
while [ "$1" != "" ];do
 if [ "$1" = "-w" ];then
  wflag='-w'
 elif echo "$1" | grep '^[0-9]*$' >/dev/null;then
  it=$1
 else echo "invalid arg $1";fi
 shift
done

ql='^-\|^< '
qr='^+\|^> '
line=$(sed 's/\x1b\[[0-9;]*m//g' < /dev/stdin)
while [ $it -gt 0 ];do
line=$(diff $wflag <(echo "$line" | grep -G $ql | sed -e 's/^-\|^< //') <(echo "$line" | grep -G $qr | sed -e 's/^+\|^> //'))
it=$(($it - 1))
ql='^< '
qr='^> '
done
echo "$line"
