#!/bin/bash

if ! git rev-parse --git-dir >/dev/null 2>&1;then exit 1;fi
branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" = "HEAD" ];then
 if [ -e '.git/rebase-merge' ];then branch=$(<.git/rebase-merge/head-name)
 elif [ -e '.git/rebase-apply' ];then branch=$(<.git/rebase-apply/head-name)
 fi
fi
echo $branch | sed -e 's/^[^0-9]*\([0-9]*\).*/\1/'
