#!/bin/bash

dir=$(git rev-parse --git-dir)
if [ -e "$dir/CHERRY_PICK_HEAD" ];then
  target=$(cat "$dir/CHERRY_PICK_HEAD")
elif [ -e "$dir/rebase-apply/original-commit" ];then
  target=$(cat "$dir/rebase-apply/original-commit")
elif [ -e "$dir/rebase-merge/stopped-sha" ];then
  target=$(cat "$dir/rebase-merge/stopped-sha")
elif [ -e "$dir/sequencer/todo" ];then
  target=$(cat "$dir/sequencer/todo" | head -1 | awk '{print $2}')
fi

git log -1 $target "$@"
