#!/bin/bash

if [ "$1" = "--help" -o "$1" = "-h" ];then
 cat << _END_
usage: git ${0##*/git-} [<commit>] [<options>..]
 show logs of merged branch

 <commit>
  merge commit that merged branch (default HEAD)
 <options>
  same as options for git-log
_END_
 exit 0
fi
if [ "$1" = "" ];then
 hash=HEAD
else
 hash=$1
fi
git rev-parse "$hash" -- 1>/dev/null 2>/dev/null
if [ $? -gt 0 ];then echo -en "'$hash' is not something represents commit\nuse -h or --help for help\n";exit;fi
shift
if [ "$(git log -1 "$hash" --pretty='%p' -- | sed -e '/ /d')" = "" ];then
 git log "$hash^1..$hash" "$@"
else
 echo "$hash" is not a merge-commit.
fi
