#!/bin/bash

dir=$(git rev-parse --git-dir)
if [ -e "$dir/sequencer" ];then
 if ! git diff --exit-code;then
  exit 1
 elif git diff --cached --quiet;then
  git cherry-pick --skip
 else
  git commit --reuse-message="$(cat "$dir/CHERRY_PICK_HEAD")"
  git cherry-pick --continue
 fi
 exit
fi
if git diff-index --quiet HEAD;then
 git rebase --skip
 exit
fi
if git diff --cached --quiet;then
 :
elif [ -e "$dir/rebase-merge/stopped-sha" ];then
 git commit --reuse-message="$(cat "$dir/rebase-merge/stopped-sha")"
elif [ -e "$dir/REVERT_HEAD" ];then
 git commit --reuse-message="$(cat "$dir/REVERT_HEAD")"
 exit
fi
if [ $? -eq 0 ];then
 git rebase --continue
fi
