#!/bin/bash

if ! git rev-parse --git-dir 2>/dev/null;then echo 'not in git';exit 1;fi
if [ -e $(git rev-parse --git-path 'rebase-merge') ];then
 cat $(git rev-parse --git-path 'rebase-merge/head-name') | sed -e 's!^befs/heads!!'
elif [ -e $(git rev-parse --git-path 'dir/rebase-apply') ];then
 cat $(git rev-parse --git-path 'rebase-apply/head-name') | sed -e 's!^refs/heads!!'
else
 git symbolic-ref --short HEAD
fi
