#!/bin/bash

args=()
dargs=()
while [ $# -gt 0 ];do
  if [ ${1:0:3} = '-d-' ];then
    dargs=("${dargs[@]}" "${1:2}")
  else
    args=("${args[@]}" "$1")
  fi
  shift
done

diff "${dargs[@]}" <(git log-theirs --patch "${args[@]}") <(git diff --cached "${args[@]}")
