#!/bin/bash

if [ "${GITHUB_TOKEN}" = "" ];then echo GITHUB_TOKEN required;exit 1;fi
if ! git rev-parse --git-dir >/dev/null 2>&1;then echo use inside git;exit 1;fi
branch=""
all=""
while [ $# -gt 0 ];do
  if [ "${1:0:1}" = "-" ];then
    if [ $1 = "-a" -o $1 = "--all" ];then
      all=1
    fi
  else
    if [ "$branch" = "" ];then
      branch=$1
    fi
  fi
  shift
done
if [ "$branch" = "" -a "$all" = "" ];then echo -e "usage: ./${0##*/} branch\n get pull-request name and labels\n\n options:\n  -a, --all";exit;fi

repo=$(git config 'remote.origin.url'|sed 's/.*://')
if [ "$all" != "" ];then
  query='{"query":"query{repository(owner:\u0022'${repo%/*}'\u0022,name:\u0022'${repo#*/}'\u0022){pullRequests(states:OPEN,first:99){nodes{headRefName,url,title,labels(first:9){nodes{name}}}}}}"}'
else
  query='{"query":"query{repository(owner:\u0022'${repo%/*}'\u0022,name:\u0022'${repo#*/}'\u0022){pullRequests(headRefName:\u0022'${branch}'\u0022,first:9){nodes{url,title,labels(first:9){nodes{name}}}}}}"}'
fi
curl -s -H 'Authorization: bearer '${GITHUB_TOKEN} -X POST -d $query 'https://api.github.com/graphql'
