#!/bin/bash

if git diff-index --quiet HEAD;then
 git rebase --skip
 exit
fi
if git diff --cached --quiet;then
 :
elif [ -e "$dir/rebase-merge/stopped-sha" ];then
 git commit -C $(cat "$dir/rebase-merge/stopped-sha")
elif [ -e "$dir/REVERT_HEAD" ];then
 git commit -C $(cat "$dir/REVERT_HEAD")
 exit
fi
if [ $? -eq 0 ];then
 git rebase --continue
fi
