#!/bin/bash

if ! git rev-parse --git-dir >/dev/null;then exit 1;fi
branch=$(git symbolic-ref --short HEAD 2>/dev/null)
if [ "$branch" != "" ] && git show-ref --quiet "origin/$branch";then
 git log "origin/$branch".. --reverse "$@"
else
 git log `git merge-base origin HEAD`..  --reverse "$@"
fi
