#!/bin/bash

git for-each-ref --format='%(refname:short)' refs/heads|grep $GIT_BRANCH_PREFIX'_[0-9]'|while read line;do
if git show-ref -q origin/$line;then echo -ne "\x1b[34m";fi
echo -n $line
if git show-ref -q origin/$line;then echo -ne "(pushed)\x1b[m";fi
echo
git l "$@" origin..$line
done
