#!/bin/bash

if [ "$1" = "" -o "$1" = "--help" -o "$1" = "-h" ];then echo -en "usage: ${0##*/} hash [options..]\n git log find -- find branch in which target hash contributes\n\n options:\n  options for git-log\n";exit 0;fi
hash=$1
type=$(git cat-file $hash -t)
if [ "$type" != 'commit' ];then echo -en "'$hash' is not something represents commit\nuse -h or --help\n";exit;fi
shift
head=$(git rev-parse HEAD)
hash=$(git rev-parse $hash)
prevhead=$head
while [ "$(git log -1 $head --pretty='%p')" != "" -a "$(git log -1 $head..$hash --pretty='%H')" != $hash ];do
 prevhead=$head
 while [ $head = $prevhead -o "$(git log -1 $head --pretty='%p'|sed -e '/ /p;d')" = "" ];do
  head=$(git rev-parse $head^1 2>/dev/null)
  if [ $head = $hash ];then break;fi
 done
done
echo $prevhead
