#!/bin/bash

if [ "$1" = "" ];then
 echo -en '$0 dir [option] [command]\noption:\n -d name : dir path of .git\n'
fi
dir=$1
shift
if [ "${dir:0:1}" != "/" ];then dir=$(pwd)'/'${dir};fi
array=()
gitdir=".git"
while [ "$1" != "" ];do
 if [ "$1" = "-d" ];then
  shift
  gitdir=$1
 else
  array+=("$1")
 fi
 shift
done
if [ "${gitdir:0:1}" != "/" ];then
 gitdir=$dir/$gitdir
fi
git -C $dir --git-dir=$gitdir "${array[@]}"
