#!/bin/bash

if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ];then
 cat << _END_
${0##*/} dir [option] [command]
run git on other dir.
require git >= 1.8.5 to use.
command: command to pass to git
option:
 -d name : dir path of .git
 -h : show this help
_END_
 exit
fi
dir=$1
shift
if [ "${dir:0:1}" != "/" ];then dir=$(pwd)'/'${dir};fi
array=()
gitdir=".git"
while [ "$1" != "" ];do
 if [ "$1" = "-d" ];then
  shift
  gitdir=$1
 else
  array+=("$1")
 fi
 shift
done
if [ "${gitdir:0:1}" != "/" ];then
 gitdir="$dir/$gitdir"
fi
git -C "$dir" --git-dir="$gitdir" "${array[@]}"
