#!/bin/bash

unset from relto absto usegit copy symlink reverse

while [ $# -gt 0 ];do
 if [ "${1:0:1}" = "-" ];then
  if [ "${1:1:1}" != "-" -a "${1/g/}" != "$1" ] || [ "$1" = "--git" ];then
   usegit=1
  fi
  if [ "${1:1:1}" != "-" -a "${1/c/}" != "$1" ] || [ "$1" = "--copy" ];then
   copy=1
  fi
  if [ "${1:1:1}" != "-" -a "${1/s/}" != "$1" ] || [ "$1" = "--symlink" ];then
   symlink=1
  fi
  if [ "${1:1:1}" != "-" -a "${1/r/}" != "$1" ] || [ "$1" = "--reverse" ];then
   reverse=1
  fi
 elif [ "$from" = "" ];then
  from=$1
 elif [ "$relto" = "" ];then
  relto=$1
 fi
 shift
done

if [ "$relto" = "" ];then cat << END;exit 1;fi
usage:
 ${0##*/} [option] file-to-move relative-path

option:
 --git
 --symlink
 --copy
 --reverse
END

absto=$(dirname "$from")'/'$relto
if [ "${absto: -1:1}" = '/' ];then absto=$absto$(basename "$from");fi
if [ "$reverse" != "" ];then tmp=$absto;absto=$from;from=$tmp;fi

if [ ! -e "$from" ];then echo 'file '$from' not exist.';exit 2;fi
if [ -e "$absto" ];then
 read -p 'file '"$absto"' exists. override? ' override
 if [ "${override:0:1}" != "y" ];then exit 2;fi
 if [ "$from" != "$absto" ];then unlink "$absto";fi
fi

function copy(){
 local from=$1 absto=$2
 if [ -d "$from" ];then
  mkdir "$absto"
  builtin ls "$from"|while read f;do copy "$from/$f" "$absto/$f";done
 else
  cat "$from" > "$absto"
 fi
}
function gitdir(){
 local dir=$(git -C "${1%/*}" rev-parse --show-toplevel)
 if [ $? -ne 0 ];then exit $?;fi
 echo $dir
}

if [ "$copy" != "" ];then
 copy "$from" "$absto"
 if [ "$usegit" != "" ];then
  dir=$(gitdir "$from")
  git -C "$dir" add -- "${absto#$dir/}"
 fi
elif [ "$usegit" != "" ];then
 dir=$(gitdir "$from")
 if [ $(uname) = 'Darwin' -a $(tr '[A-Z]' '[a-z]' <<< "$from") = $(tr '[A-Z]' '[a-z]' <<< "$absto") ];then force='--force';fi
 git -C "$dir" mv $force "${from#$dir/}" "${absto#$dir/}"
else
 mv "$from" "$absto"
fi

if [ "$symlink" != "" ];then
 ln -s "$absto" "$from"
 if [ "$usegit" != "" ];then
  git add -- "$from"
 fi
fi
