#!/bin/bash

if [ ! -p /dev/stdin ];then echo stdin required;exit 1;fi
if [ $# -lt 1 ];then echo require arg 1;exit 1;fi
s=$1
e=$2
if [ $# -lt 2 ];then e=$s;s=0;fi
perl -pe 's/^.{'$s'}((?:[\x00-\x7f]|[\x80-\xdf]|[\xe0-\xef].|[\xf0-\xff]..){0,'$e'})(?![\x80-\xbf]).*/$1/'
