#!/bin/bash

if [ ! -p /dev/stdin ];then echo stdin required;exit 1;fi
if [ $# -lt 1 ];then echo require arg 1;exit 1;fi
s=$1
e=$2
if [ $# -lt 2 ];then e=$s;s=1;else s=$(($s+1));e=$(($s+$e));fi
cut -b "$s-$e"
