#!/usr/bin/env perl

if($ARGV[0]<1){print "require arg 1\n";exit 1;}
if($ARGV[1]){$s=$ARGV[0];$e=$ARGV[1];}else{$s=0;$e=$ARGV[0];}
while(<STDIN>){chomp;my($p,$ee);$ee=$e;while($ee<length($_)){$p=ord(substr($_,$ee,1));if($p>127 && $p<192){$ee++;}else{last;}}print substr($_,$s,$ee)."\n";}
